#!/usr/bin/env sh

# Load the scripting addition
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# -- global --------------------------------------------------------------------
yabai -m config active_window_opacity       1.0
yabai -m config normal_window_opacity       1.0
yabai -m config window_animation_duration   0.0
yabai -m config window_opacity_duration     0.0
yabai -m config window_shadow               on
yabai -m config window_zoom_persist         off
yabai -m config split_ratio                 0.5
yabai -m config split_type                  auto
yabai -m config layout                      bsp
yabai -m config top_padding                 8 
yabai -m config bottom_padding              8 
yabai -m config left_padding                8  
yabai -m config right_padding               8  
yabai -m config window_gap                  10 

# -- rules ---------------------------------------------------------------------
# don't manage apps by default
yabai -m rule --add app=".*" manage=off
# managed apps
yabai -m rule --add label="Ghostty" app="^Ghostty$" manage=on

# --- signals ------------------------------------------------------------------
# signal sketchybar when window zoom state changes
yabai -m signal --add event=window_resized \
  action="sketchybar --trigger window_changed"
yabai -m signal --add event=window_destroyed \
  action="sketchybar --trigger window_changed"
yabai -m signal --add event=space_changed \
  action="sketchybar --trigger window_changed"
