# -- general -------------------------------------------------------------------

# ensure vim colorscheme carries over in tmux
# set -g default-terminal "screen-256color"
# if 'infocmp -x tmux-256color > /dev/null 2>&1' 'set -g default-terminal "tmux-256color"'

# set vi mode keys
setw -g mode-keys vi
set-option -g status-keys vi

# begin window indexing at 1
set -g base-index 1

# history-limit scrollback in terminal
set-option -g history-limit 3000

# reload configuration
bind r source-file ~/.tmux.conf \; display '~/.tmux.conf sourced'

# -- display -------------------------------------------------------------------

set-option -g status-position bottom
set-option -g status-style bg="#eeeeee",fg="#444444"

# start windows and pane numbering at 1
set -g base-index 1
setw -g pane-base-index 1

# renumber windows when a window is closed
set -g renumber-windows on

# slightly longer pane indicators display time
set -g display-panes-time 800 
# slightly longer status messages display time
set -g display-time 1000

# redraw status line every 10 seconds
set -g status-interval 10

# quiet
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# pane resizing
bind -r H resize-pane -L 10
bind -r J resize-pane -D 10
bind -r K resize-pane -U 10
bind -r L resize-pane -R 10

# allow resizing of panes with mouse
set -g mouse on

# found this online, don't understand what it does yet:
# "Rather than constraining window size to the maximum size of any client
# connected to the *session*, constrain window size to the maximum size of any
# client connected to *that window*. Much more reasonable."
# setw -g aggressive-resize on

# tile all windows
# unbind =
# bind = select-layout tiled

# -- navigation ----------------------------------------------------------------

# find session
bind C-f command-prompt -p find-session 'switch-client -t %%'

# split current window horizontally
# bind s split-window -v -c "#{pane_current_path}"
# split current window vertically
# bind v split-window -h -c "#{pane_current_path}"
# bind c new-window -c "#{pane_current_path}"

bind s split-window -v
bind v split-window -h

# pane navigation
bind -r h select-pane -L  # move left
bind -r j select-pane -D  # move down
bind -r k select-pane -U  # move up
bind -r l select-pane -R  # move right
bind > swap-pane -D       # swap current pane with the next one
bind < swap-pane -U       # swap current pane with the previous one

# maximize current pane
# bind + run 'cut -c3- ~/.tmux.conf | sh -s _maximize_pane "#{session_name}" #D'
