(deftheme Papercolor
  "Created 2021-12-23. Uses the same colors from the Papercolor scheme for Vim.")

(custom-theme-set-faces
 'Papercolor
 '(default ((t (:family "Menlo" :foundry "nil" :width normal :height 120 :weight normal :slant normal :underline nil :overline nil :extend nil :strike-through nil :box nil :inverse-video nil :foreground "#505050" :background "#FFFFFF" :stipple nil :inherit nil))))
 '(cursor ((t (:inverse-video t :foreground "#f2f2f2" :background "#F57F17"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((t (:weight bold :foreground "#a66bab" :background "#f8f1f8"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:weight bold :foreground "#cf7900" :background "#fdf9f2"))))
 '(highlight ((t (:foreground "#417598" :background "#e3f4ff"))))
 '(region ((t (:extend t :foreground "#f2f2f2" :background "#c7e1f2"))))
 '(shadow ((t nil)))
 '(secondary-selection ((t (:weight bold :extend t :background "#808080"))))
 '(trailing-whitespace ((t (:foreground "#4271ae" :background "#3e999f"))))
 '(font-lock-builtin-face ((t (:foreground "#d2ad00" :background "#faf7e7"))))
 '(font-lock-comment-delimiter-face ((t (:weight normal :foreground "#4d4d4c"))))
 '(font-lock-comment-face ((t (:weight normal :slant italic :foreground "#a49da5" :background "#f7f7f7"))))
 '(font-lock-constant-face ((t (:foreground "#a66bab" :background "#f8f1f8"))))
 '(font-lock-doc-face ((t (:weight normal :slant italic :foreground "#a49da5" :background "#f7f7f7"))))
 '(font-lock-function-name-face ((t (:foreground "#d15120" :background "#fdf2ed"))))
 '(font-lock-keyword-face ((t (:weight bold :foreground "#cf7900" :background "#fdf9f2"))))
 '(font-lock-negation-char-face ((t (:foreground "#d2ad00" :background "#faf7e7"))))
 '(font-lock-preprocessor-face ((t (:foreground "#cf7900" :background "#fdf9f2"))))
 '(font-lock-regexp-grouping-backslash ((t (:weight bold :foreground "#4271ae" :inherit nil))))
 '(font-lock-regexp-grouping-construct ((t (:weight bold :foreground "#d7005f" :inherit nil))))
 '(font-lock-string-face ((t (:foreground "#5f9411" :background "#eff8e9"))))
 '(font-lock-type-face ((t (:weight normal :foreground "#b23f1e" :background "#fcf3f1"))))
 '(font-lock-variable-name-face ((t (:weight normal :foreground "#6b82a7" :background "#f1f4f8"))))
 '(font-lock-warning-face ((t (:weight bold :foreground "#d15120" :background "#fdf2ed"))))
 '(button ((t (:underline (:color foreground-color :style line) :foreground "#2f7e9d"))))
 '(link ((t (:underline (:color foreground-color :style line) :foreground "#6b82a7" :background "#f1f4f8"))))
 '(link-visited ((t (:underline (:color foreground-color :style line) :foreground "#d7005f" :inherit (link)))))
 '(fringe ((t (:foreground "#454545" :background "#f7f7f7"))))
 '(header-line ((t (:box (:line-width 1 :color "#2f7e9d" :style nil) :foreground "#d7005f" :inherit (mode-line)))))
 '(tooltip ((t (:foreground "#546E7A" :background "#ffffffffffff"))))
 '(mode-line ((t (:height 0.95 :box nil :foreground "#417598" :background "#e3f4ff"))))
 '(mode-line-buffer-id ((t (:weight bold :foreground "#d7005f"))))
 '(mode-line-emphasis ((t (:slant italic :foreground "#f3f3f3"))))
 '(mode-line-highlight ((t (:weight bold :box nil :foreground "#d7005f" :background "#fffbc4"))))
 '(mode-line-inactive ((t (:height 0.95 :box nil :foreground "#a49da5" :background "#eaeaea"))))
 '(isearch ((t (:inverse-video t :foreground "#4271ae" :background "#262626" :inherit (match)))))
 '(isearch-fail ((t (:weight bold :inverse-video t :foreground "#f2f2f2" :background "#262626" :inherit (font-lock-warning-face)))))
 '(lazy-highlight ((t (:foreground "#454545" :background "#fffbc4"))))
 '(match ((t (:weight bold :inverse-video t :foreground "#005f87" :background "#262626"))))
 '(next-error ((t (:background "#90A4AE" :inherit (error)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'Papercolor)
